server:
  port: ${APP_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: ${APP_PORT:8080}


resilience4j:
  retry:
    instances:
      createCustomerFallBackRetry:
        max-attempts: 3
        wait-duration: 1000ms
        retry-exceptions:
          - pe.seek.app.shared.exception.EntityWrapperException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
jwt:
  secret: ${JWT_SECRET:ZQBzAHQAZQB0AHIAYQBiAGEAagBvAHMAZQByAGEAbQBpAG8AeQBtAGUAZwBhAG4AYQByAGUAMQAwAG0A}
  expiration: ${JWT_EXPIRATION:14400000}

spring:
  application:
    name: app-customer
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:db_app_customer}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${APP_ENVIRONMENT:dev}